name: Add docs to docs project

on:
  issues:
    types:
      - labeled

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@main
        with:
          project-url: https://github.com/orgs/developerka/projects/1
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
          labeled: docs, 6.1
          label-operator: OR
